### ISSUE TITLE
webui doesn't work

### ISSUE THREAD

**Issue by DavidDah** [tomchang25/whisper-auto-transcribe#47]
When using transcribe or translation browser reports error and this is output from console:

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe\src\utils\task.py", line 108, in transcribe
    subprocess.run(cmd, check=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe\venv\lib\site-packages\gradio\blocks.py", line 1303, in process_api
    result = await self.call_function(
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe\venv\lib\site-packages\gradio\blocks.py", line 1026, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe\src\transcribe_gui.py", line 327, in handle_form_submit
    subtitle_file_path = task.transcribe(
  File "C:\Users\user\Downloads\autotranscribe\whisper-auto-transcribe\src\utils\task.py", line 110, in transcribe
    raise Exception(
Exception: Error. Vocal extracter unavailable. Received:
C:\Users\user\AppData\Local\Temp\bebf2e05e25135efa50c8a746b06c2875e007655\IMG_5503.MP4, C:\Users\user\AppData\Local\Temp\tempfreesubtitle\main.MP4, C:\Users\user\AppData\Local\Temp
demucs --two-stems=vocals "C:\Users\user\AppData\Local\Temp\tempfreesubtitle\main.MP4" -o "C:\Users\user\AppData\Local\Temp" --filename "{stem}.{ext}"

**Comment by tomchang25** [comment]
Hi, @DavidDah. I can't reproduce the issue in the same filename.

- How big is the file size?
- Could you please check if the file `C:\Users\user\AppData\Local\Temp\tempfreesubtitle\main.MP4` exists?
- Additionally, could you check if the file `C:\Users\user\AppData\Local\Temp\bebf2e05e25135efa50c8a746b06c2875e007655\IMG_5503.MP4` exists as well?"
- Could you try renaming the original file, `IMG_5503.MP4`, to lowercase and then try again?

**Comment by mxgc** [comment]
I've run into the same problem as well `Vocal extracter unavailable`.

The error can be bypassed by setting `vocal_extractor` to `False` on Line 27 in `src/util/task.py`. (Of course this doesn't solve the underlying issue.)

It might be a good idea to add a new argument in `cli.py`, allowing user to set `vocal_extractor` status.

**Comment by matheus2740** [comment]
Same problem here, I bypassed it by disabling the vocal extractor as mxgc suggested, but I would like to have a better solution. Could this explain why my subtitles are not very well synced? or the vocal extractor is just a cleanup pass that doesn't interfere with syncing?
