### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Cerzs** [tomchang25/whisper-auto-transcribe#48]
Hello. Getting this error after installing.

Log:

venv "F:\whisper-auto-transcribe\venv\Scripts\Python.exe"
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
Commit hash: 0f023b4cbf276df66f3303b2f10c41c753ef96ac
Check torch and torchvision
Check gradio
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "F:\whisper-auto-transcribe\launch.py", line 244, in <module>
    start_webui()
  File "F:\whisper-auto-transcribe\launch.py", line 238, in start_webui
    from gui import gui
  File "F:\whisper-auto-transcribe\gui.py", line 1, in <module>
    from src import transcribe_gui
  File "F:\whisper-auto-transcribe\src\transcribe_gui.py", line 7, in <module>
    from src.utils import task
  File "F:\whisper-auto-transcribe\src\utils\task.py", line 8, in <module>
    import stable_whisper
  File "F:\whisper-auto-transcribe\venv\lib\site-packages\stable_whisper\__init__.py", line 1, in <module>
    from .whisper_word_level import *
  File "F:\whisper-auto-transcribe\venv\lib\site-packages\stable_whisper\whisper_word_level.py", line 8, in <module>
    import whisper
  File "F:\whisper-auto-transcribe\venv\lib\site-packages\whisper\__init__.py", line 13, in <module>
    from .model import ModelDimensions, Whisper
  File "F:\whisper-auto-transcribe\venv\lib\site-packages\whisper\model.py", line 13, in <module>
    from .transcribe import transcribe as transcribe_function
  File "F:\whisper-auto-transcribe\venv\lib\site-packages\whisper\transcribe.py", line 20, in <module>
    from .timing import add_word_timestamps
  File "F:\whisper-auto-transcribe\venv\lib\site-packages\whisper\timing.py", line 7, in <module>
    import numba
  File "F:\whisper-auto-transcribe\venv\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "F:\whisper-auto-transcribe\venv\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "F:\whisper-auto-transcribe\venv\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

**Comment by tomchang25** [comment]
Hi @Cerzs.
It looks like Stable Whisper has broken again. I will remove it as the default model for now.
