### ISSUE TITLE
what it is?

### ISSUE THREAD

**Issue by ddddwq2q** [tomchang25/whisper-auto-transcribe#50]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\whisper-auto-transcribe-main\new\whisper-auto-transcribe\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\whisper-auto-transcribe-main\new\whisper-auto-transcribe\venv\lib\site-packages\gradio\blocks.py", line 1303, in process_api
    result = await self.call_function(
  File "D:\whisper-auto-transcribe-main\new\whisper-auto-transcribe\venv\lib\site-packages\gradio\blocks.py", line 1026, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\whisper-auto-transcribe-main\new\whisper-auto-transcribe\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\whisper-auto-transcribe-main\new\whisper-auto-transcribe\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\whisper-auto-transcribe-main\new\whisper-auto-transcribe\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\whisper-auto-transcribe-main\new\whisper-auto-transcribe\src\transcribe_gui.py", line 327, in handle_form_submit
    subtitle_file_path = task.transcribe(
  File "D:\whisper-auto-transcribe-main\new\whisper-auto-transcribe\src\utils\task.py", line 110, in transcribe
    raise Exception(
Exception: Error. Vocal extracter unavailable. Received:
C:\Users\73B5~1\AppData\Local\Temp\6a2c5585a48a66a68c6f1a9593cb8d763b9e0aad\Не хочу-0-100.mp3, C:\Users\73B5~1\AppData\Local\Temp\tempfreesubtitle\main.mp3, tmp/2023-05-19 23-39-52
demucs --two-stems=vocals "C:\Users\73B5~1\AppData\Local\Temp\tempfreesubtitle\main.mp3" -o "tmp/2023-05-19 23-39-52" --filename "{stem}.{ext}"

(this error crashes immediately when you go to the result page)

**Comment by Peter5Chiou** [comment]
install demucs may solve this problem.

enable_venv.bat
pip install demucs
