### ISSUE TITLE
unexpected keyword argument 'caption'

### ISSUE THREAD

**Issue by JD-2006** [tomchang25/whisper-auto-transcribe#7]
Getting error:
cuda:0
Detected language: English
100%|███████████████████████████████████████████████████████████████████| 69968/69968 [02:45<00:00, 422.93frames/s]
tmp/Updated ｜ Near-Automated Voice Cloning ｜ Whisper STT + Coqui TTS ｜ Fine Tune a VITS Model on Colab.srt tmp/Updated ｜ Near-Automated Voice Cloning ｜ Whisper STT + Coqui TTS ｜ Fine Tune a VITS Model on Colab.vtt tmp/Updated ｜ Near-Automated Voice Cloning ｜ Whisper STT + Coqui TTS ｜ Fine Tune a VITS Model on Colab.ass
Traceback (most recent call last):
  File "C:\Users\CHP_7575\Documents\whisper-auto-transcribe\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\CHP_7575\Documents\whisper-auto-transcribe\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\CHP_7575\Documents\whisper-auto-transcribe\venv\lib\site-packages\gradio\blocks.py", line 947, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "C:\Users\CHP_7575\Documents\whisper-auto-transcribe\venv\lib\site-packages\gradio\blocks.py", line 371, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "C:\Users\CHP_7575\Documents\whisper-auto-transcribe\venv\lib\site-packages\gradio\blocks.py", line 257, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Video.update() got an unexpected keyword argument 'caption'

Tried running inside venv and without. Tried different gradio versions as well. Does not work for me on .mp3's or using YT vid.

**Comment by tomchang25** [comment]
will fix after gradio fork merge.

**Comment by tomchang25** [comment]
Update to v2.1
